# Run:
#   $ docker-compose --profile <NAME_OF_PROFILE> up
# Profiles:
#   - database. Only the database is deployed.
#   - back-end. Only the database and back-end are deployed.
# Ports:
#   - Back-end:   8080
#   - Timescale DB:  5432

version: '3.7'

services:

  # Back-end
  back-end:
    image: ullsoftware/truck-planner_back-end:latest
    container_name: truck-planner
    ports:
      - '8080:8080'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://timescaledb:5432/truckplanner
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
    depends_on:
      - timescaledb
    profiles: ['back-end', 'production']

  # Timescale DB
  timescaledb:
    image: timescale/timescaledb:latest-pg15
    container_name: timescaledb
    ports:
      - 5432:5432    
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DATABASE: truckplanner
    profiles: ['database', 'back-end', 'production']

  # Watchtower
  #watchtower:
  #  image: containrrr/watchtower
  #  container_name: watchtower
  #  restart: always    
  #  environment:
  #    WATCHTOWER_CLEANUP: "true"
  #    WATCHTOWER_DEBUG: "true"
  #  volumes:
  #    - /var/run/docker.sock:/var/run/docker.sock
  #  command: --interval 30